from gemjam import GEMJAM

PROCESS_SINGLE_VIDEO = False
ENABLE_SCRAPING_MODE = False
ENABLE_ANALYSIS_MODE = False
ENABLE_UPLOAD_MODE = True
UPLOAD_LIMIT = 0
VIDEOS_TO_PROCESS_COUNT = 50
GEMINI_API_KEY = GEMJAM